services:
  - type: web
    name: beyond-classroom-backend
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ZOOM_ACCOUNT_ID
        sync: false
      - key: ZOOM_CLIENT_ID
        sync: false
      - key: ZOOM_CLIENT_SECRET
        sync: false
      - key: ZOOM_USER_ID
        value: me
      - key: RAZORPAY_KEY_ID
        value: rzp_live_SRVzzcULeXSVOl
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://beyondclassroom.netlify.app
